theme: jekyll-theme-slate
baseurl: ""
url: "https://TuringIntern2018.github.io"
title: High performance, large-scale regression
description: This blog contains guidelines and instructions to run linear and logistic regression on very large datasets in distributed settings.
